=== Kalen-W/portfolioWebsite/assets/jsonFiles/documentationOfWorks.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "meta": {
            "type":"object",
            "properties": {
                "categoryData": {
                    "type": "object",
                    "properties": {
                        "game":      {"$ref": "#/definitions/metaDataObj"},
                        "model":     {"$ref": "#/definitions/metaDataObj"},
                        "art":       {"$ref": "#/definitions/metaDataObj"},
                        "animation": {"$ref": "#/definitions/metaDataObj"},
                        "webDesign": {"$ref": "#/definitions/metaDataObj"},
                        "misc":      {"$ref": "#/definitions/metaDataObj"}
                    },
                    "required": ["game", "model", "art", "animation", "webDesign", "misc"]
                },

                "tagData": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/definitions/metaDataObj"}
                },

                "devToolData": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/definitions/metaDataObj"}
                }
            },
            "required": ["categoryData", "tagData", "devToolData"]
        },


        "games":     {"type": "array", "items": {"$ref": "#/definitions/projectData"}},
        "models":    {"type": "array", "items": {"$ref": "#/definitions/projectData"}},
        "art":       {"type": "array", "items": {"$ref": "#/definitions/projectData"}},
        "animation": {"type": "array", "items": {"$ref": "#/definitions/projectData"}},
        "webDesign": {"type": "array", "items": {"$ref": "#/definitions/projectData"}},
        "misc":      {"type": "array", "items": {"$ref": "#/definitions/projectData"}}
    },

    "required": ["meta", "games", "models", "art", "animation", "webDesign", "misc"],




    "definitions": {
        "projectData": {
            "type": "object",
            "properties": {
                "id":               {"type": "string"},
                "title":            {"type": "string"},
                "category":         {
                    "type": "string",
                    "enum": ["game", "model", "art", "animation", "webDesign", "misc"]
                },
                "date_devStart":    {"type": "string"},
                "date_devEnd":      {"type": "string"},
                "tags":             {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {"type": "string"}
                },
                "devTools":         {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {"type": "string"}
                },
                "links":            {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {"$ref": "#/definitions/resourceData"}
                },
                "desc_brief":       {"type": "string"},
                "desc_detailed":    {"type": "string"},
                "img_thumbnail":    {"$ref": "#/definitions/resourceData"},
                "slideshowSlides":  {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {"$ref": "#/definitions/resourceData"}
                },
                "relatedWorks":     {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {"type": "string"}
                },
                "credits":          {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {"$ref": "#/definitions/resourceData"}
                },
                "priority":         {"type": "integer"},
                "enabled":          {"type": "boolean"}
            },
            "required": ["id", "title", "category", "tags", "devTools", "desc_brief", "desc_detailed", "img_thumbnail", "enabled"]
        },



        "resourceData": {
            "type": "object",
            "properties": {
                "url":             {"type": "string"},
                "type":            {
                    "type": "string",
                    "enum": ["image", "video", "youtubeVideo", "webPage", "download"]
                },
                "absoluteUrl":     {"type": "boolean"},
                "displayName":     {"type": "string"},
                "desc":            {"type": "string"},
                "subResourceData": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/definitions/resourceData"}
                },
                "imageRendering":  {
                    "type": "string",
                    "enum": ["auto", "crisp-edges", "pixelated"]
                }
            },
            "required": ["url", "type"]
        },


        "metaDataObj": {
            "type": "object",
            "properties": {
                "id":                   {"type": "string"},
                "displayName":          {"type": "string"},
                "displayName_plural":   {"type": "string"},
                "desc":                 {"type": "string"}
            },
            "required": ["displayName", "desc"]
        }
    }
}

=== Kalen-W/portfolioWebsite/assets/jsonFiles/documentationOfWorks.json
{
    "$schema": "./documentationOfWorks.schema.json",
    "meta": {
        "featuredWorkIds": ["untitledBowGame", "jsRaycastEngine", "projectUndeadStrategy", "introToAnimationFlipbook"],

        "categoryData": {
            "game": { "id": "game",
                "displayName": "Game Project",
                "displayName_plural": "Game Projects",
                "desc": "Video games and things that aspired to be video games."
            },
            "gameDesign": { "id": "gameDesign",
                "displayName": "Game Design",
                "desc": "Things related to game design, such as game design documents or level design sketches."
            },
            "model": { "id": "model",
                "displayName": "3D Model",
                "displayName_plural": "3D Models",
                "desc": "3D models."
            },
            "art": { "id": "art",
                "displayName": "2D Art",
                "desc": "2D Art, either created physically or digitally."
            },
            "animation": { "id": "animation",
                "displayName": "Animation",
                "displayName_plural": "Animations",
                "desc": "2D and 3D animations."
            },
            "webDesign": { "id": "webDesign",
                "displayName": "Web Design",
                "desc": "Websites."
            },
            "misc": { "id": "misc",
                "displayName": "Miscellaneous",
                "desc": "Projects that don't fit neatly into any other category."
            }
        },


        "tagData": {
            "firstPerson": { "id": "firstPerson",
                "displayName": "First-Person",
                "desc": "Displayed from a first-person camera perspective."
            },
            "thirdPerson": { "id": "thirdPerson",
                "displayName": "Third-Person",
                "desc": "Displayed from a third-person camera perspective."
            },
            "topDown": { "id": "topDown",
                "displayName": "Top-Down",
                "desc": "Displayed from a top-down camera perspective."
            },
            "sideScroller": { "id": "sideScroller",
                "displayName": "Side-Scroller",
                "desc": "Displayed from a side-view camera perspective."
            },
            "isometric": { "id": "isometric",
                "displayName": "Isometric",
                "desc": "Displayed from a isometric projection based camera perspective."
            },

            "action": { "id": "action",
                "displayName": "Action",
                "desc": "Emphasizes physical challenges, such as hand-eye coordination & reaction time."
            },
            "strategy": { "id": "strategy",
                "displayName": "Strategy",
                "desc": "Emphasizes decision-making skills and complex strategical thinking."
            },
            "turnBased": { "id": "turnBased",
                "displayName": "Turn-Based",
                "desc": "Gameplay takes place within distinct turns."
            },
            "puzzle": { "id": "puzzle",
                "displayName": "Puzzle",
                "desc": "Is either directly a puzzle, or a game with an emphasis on solving puzzles."
            },

            "shooter": { "id": "shooter",
                "displayName": "Shooter",
                "desc": "A subgenre of action games, defined by the use of projectile weaponry, generally being used to defeat enemies."
            },
            "rogueLike": { "id": "rogueLike",
                "displayName": "Rogue-Like",
                "desc": "A subgenre of role-playing games, primarily defined by procedurally generated environments and permanent death of the player character."
            },

            "physicalSketch": { "id": "physicalSketch",
                "displayName": "Sketch",
                "desc": "A sketch drawn using physical mediums."
            },
            "digitalSketch": { "id": "digitalSketch",
                "displayName": "Digital Sketch",
                "desc": "A sketch drawn using digital software."
            },
            "pixelArt": { "id": "pixelArt",
                "displayName": "Pixel Art",
                "desc": "Digital art with importance placed on individual pixels."
            },

            "modelWeapon": { "id": "modelWeapon",
                "displayName": "Weapon Model",
                "desc": "A 3D model depicting some form of weaponry."
            },
            "3dEnvironment": { "id": "3dEnvironment",
                "displayName": "3D Environment",
                "desc": "A designed environment created within a 3D space."
            }
        },


        "devToolData": {
            "html": { "id": "html",
                "displayName": "HTML",
                "desc": "(HyperText Markup Language) The standard markup language for documents displayed in a web browser."
            },
            "css": { "id": "css",
                "displayName": "CSS",
                "desc": "(Cascading Style Sheets) A style sheet language for describing the presentation of a markup document."
            },
            "javaScript": { "id": "javaScript",
                "displayName": "JavaScript",
                "desc": "An object-oriented programming language used to create interactive webpage behavior."
            },
            "cSharp": { "id": "cSharp",
                "displayName": "C#",
                "desc": "A general-purpose high-level programming language supporting multiple paradigms."
            },

            "unity": { "id": "unity",
                "displayName": "Unity",
                "desc": "A cross-platform game engine developed by Unity Technologies."
            },

            "blender": { "id": "blender",
                "displayName": "Blender",
                "desc": "A free & open-source 3D computer graphics software used to create 3D models."
            },
            "krita": { "id": "krita",
                "displayName": "Krita",
                "desc": "A free & open-source raster graphics (image) editor."
            },
            "touchDesigner": { "id": "touchDesigner",
                "displayName": "Touch Designer",
                "desc": "An interactive design application that allows users to create real-time interactive content developed by Derivative."
            },
            "photoshop": { "id": "photoshop",
                "displayName": "Photoshop",
                "desc": "A raster graphics (image) editor developed by Adobe Inc."
            },
            "illustrator": { "id": "illustrator",
                "displayName": "Illustrator",
                "desc": "A vector graphics editor developed by Adobe Inc."
            },
            "afterEffects": { "id": "afterEffects",
                "displayName": "After Effects",
                "desc": "A visual effects, motion graphics, & video editing software developed by Adobe Inc."
            },

            "atom": { "id": "atom",
                "displayName": "Atom",
                "desc": "Was a free & open-source source-code editor made by GitHub. (No longer under development.)"
            },
            "vsCode": { "id": "vsCode",
                "displayName": "VS Code",
                "desc": "(Visual Studio Code) A source-code editor made by Microsoft."
            },

            "pencilAndPaper": { "id": "pencilAndPaper",
                "displayName": "Pencil & Paper",
                "desc": "Good old-fashion pencil and paper."
            }
        }
    },




    "games": [
        {
            "id":               "untitledBowGame",
            "title":            "Untitled Bow Game",
            "category":         "game",
            "date_devStart":    "2023-01-24",
            "date_devEnd":      "present",
            "tags":             ["puzzle", "shooter", "firstPerson"],
            "devTools":         ["cSharp", "unity", "blender", "krita", "vsCode"],
            "links":            [
                {
                    "url": "https://drive.google.com/file/d/1sbcmzxElN-dLQozvxSBByjXyn5fOy32Y/view",
                    "type": "webPage", "absoluteUrl": true,
                    "displayName": "Download Game Executable"
                }
            ],
            "desc_brief":       "A first-person puzzle game, centered around using a bow and various arrows with special effects, developed with Unity.",
